---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.



# Notes from Chapter 12
### Step 12.1

- Samara's note: I already had all of the prerequisits met, so I was able to skip over this step

- Alyvia's note: I completed this step prior to lab, so all of the prerequisites are met.

- Shiva's note: Met all the prerequisits.

- Sravya's note: Already done

- Alyvia's note: I completed this step prior so all of the prerequisites are met.

### Step 12.2
- Samara's note: Since a repo was already made for us, I did not have to go through these steps

- Shiva's note: Repository already created, mnoved on to next steps.

- Alyvia's note: This repo was made for us.

- Sravya's note: Made Repo in previous class.


### Step 12.3
- Samara's note: I followed the steps to create a new project from version control. I used the default name for the repo, and saved it into a folder titled "Labs", everything worked as expected

- Shiva's note: Followed the steps and created a new project.

- Sravya note: Created Project with no isuue 

- Alyvia's note: I followed this step and created the new project using the repo url provided.


### Step 12.4
- Samara's note: I am considering my notes from the pervious steps as changes. Now I will commit with hopefully no issues.

- Shiva's note: Succesfully commited.

- Alyvia's note: I have commited my prior notes for this step, and I will commit this note as well.

- Sravya's note: Only after saving the changes, i can use the commit command. And sent a commit message.


### Step 12.5
- Samara's note: Since I was the first to push, I was able to push without any issues.

- Shiva's note: Faced some problem pushing the changes, was not able to get the push/pull button. Had to use some git rebase commands to complete that task, and then was able to get the push/pull after kniting the Rmd file again.

- Sravya's note: unable to push after commiting the changes. Resolved it by saving the changes then kniting it into a html file and then used commands in terminal such as "git add .", "git rebase --continue" and :q to quit and resolve all the commits. then was able to use the pull and push command.

- Alyvia's note: I ran into an issue when attempting to push. This was fixed by working through and saving the changes while using the terminal to use commands like "git add ." and "git status". I then knitted the file and the push went through successfully. 


### Step 12.6
- Samara's note: I was able to see my commit message and the updated code within the GitHub remote

- Sravya's note: successfully able to see the commit message in README file.

- Alyvia's note: After refreshing the browser, I was able to see my commit message and the new line in README.

- Shiva's note: 

### Step 12.7
- Samara's note: Since we are skipping the clean up, I am making no notes.

- Alyvia's note: This step is meant to be skipped for this lab.

- Sravya's note: no note.

- Shiva's note: Asked not to delete in the instructions.

